addReviewers: true

addAssignees: author

numberOfReviewers: 1

useReviewGroups: true

reviewGroups:
  groupA:
    - anderzaj
  groupB:
    - mnfriedl

availabilityExceptions:
  monday:
    - mnfriedl
  wednesday:
    - anderzaj
  saturday:
    - mnfriedl
  sunday:
    - mnfriedl

useAssigneeGroups: false
