addReviewers: true

addAssignees: author

numberOfReviewers: 1

useReviewGroups: true

reviewGroups:
  groupA:
    - anderzaj
    - bimartinez
  groupB:
    - nmassardot

availabilityExceptions:
  monday:
    - nmassardot
  wednesday:
    - nmassardot
  friday:
    - nmassardot
    - bimartinez

useAssigneeGroups: false
